### ISSUE TITLE
LACK OF a guide teaching you how to use this Fluminurs on Windows 10 (.exe) and am super lost!!

### ISSUE THREAD

**Issue by cupcakeslove128** [indocomsoft/fluminurs#406] opened 2020-07-17 09:37 UTC
It forces close and I have no idea how to use Fluminurs as well!!

@indocomsoft

**Comment by indocomsoft** [comment] 2020-07-18 12:06
Duplicate of #405, answered in https://github.com/indocomsoft/fluminurs/issues/405#issuecomment-660473293

**Closed by indocomsoft** 2020-07-18 12:06 UTC
